[package]
name = "catalyst"
version = "0.1.0"
authors = ["Alex McArther <acmcarther@gmail.com>"]

[dependencies]
time = "*"
rustc-serialize = "0.3.16"
iron = "*"
router = "*"
staticfile = "*"
itertools = "*"
mount = "*"
rand = "*"

[dependencies.github_v3]
git = "https://github.com/acmcarther/github_v3_rust"
rev = "f387bbd"

[dev-dependencies]
expectest = "*"
