[package]
name = "catalyst"
version = "0.1.0"
authors = ["Alex McArther <acmcarther@gmail.com>"]

[dependencies]
iron = "*"
time = "*"
router = "*"
rustc-serialize = "0.3.16"

[dependencies.github_v3]
git = "https://github.com/acmcarther/github_v3_rust"
rev = "abf6e3b"
